package com.example.praveen.privacycheck.Utils;

import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.StringTokenizer;

/**
 * Created by satyamkumar on 29/11/16.
 */

public class Permissions {
    public static final String BASE_URL = "https://developer.android.com/reference/android/Manifest.permission.html";
    public static final String SEPERATOR = "#";

    public static final List<String> NORMAL_PERMISSIONS = Arrays.asList("ACCESS_LOCATION_EXTRA_COMMANDS", "ACCESS_NETWORK_STATE", "ACCESS_NOTIFICATION_POLICY",
            "ACCESS_WIFI_STATE", "BLUETOOTH", "BLUETOOTH_ADMIN", "BROADCAST_STICKY", "CHANGE_NETWORK_STATE", "CHANGE_WIFI_MULTICAST_STATE",
            "CHANGE_WIFI_STATE", "DISABLE_KEYGUARD", "EXPAND_STATUS_BAR", "GET_PACKAGE_SIZE", "INSTALL_SHORTCUT", "INTERNET",
            "KILL_BACKGROUND_PROCESSES", "MODIFY_AUDIO_SETTINGS", "NFC", "READ_SYNC_SETTINGS", "READ_SYNC_STATS", "RECEIVE_BOOT_COMPLETED",
            "REORDER_TASKS", "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "REQUEST_INSTALL_PACKAGES", "SET_ALARM", "SET_TIME_ZONE", "SET_WALLPAPER",
            "SET_WALLPAPER_HINTS", "TRANSMIT_IR", "UNINSTALL_SHORTCUT", "USE_FINGERPRINT", "VIBRATE", "WAKE_LOCK", "WRITE_SYNC_SETTINGS");

    public static final List<String> DANGEROUS_PERMISSIONS = Arrays.asList("READ_CALENDAR", "WRITE_CALENDAR", "CAMERA", "READ_CONTACTS", "WRITE_CONTACTS",
            "GET_ACCOUNTS", "ACCESS_FINE_LOCATION", "ACCESS_COARSE_LOCATION", "RECORD_AUDIO", "READ_PHONE_STATE", "CALL_PHONE",
            "READ_CALL_LOG", "WRITE_CALL_LOG", "ADD_VOICEMAIL", "USE_SIP", "PROCESS_OUTGOING_CALLS", "BODY_SENSORS", "SEND_SMS",
            "RECEIVE_SMS", "READ_SMS", "RECEIVE_WAP_PUSH", "RECEIVE_MMS", "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE");

    public static final List<String> DANGEROUS_GROUP_NAMES = Arrays.asList("CALENDAR", "CAMERA", "CONTACTS", "LOCATION", "MICROPHONE",
            "PHONE", "SENSORS", "SMS", "STORAGE");

    public static HashMap<String, List<String> > DANGEROUS_GROUPS_PERMISSIONS = new HashMap<>();

    static {
        DANGEROUS_GROUPS_PERMISSIONS.put("CALENDAR", Arrays.asList("READ_CALENDAR", "WRITE_CALENDAR"));
        DANGEROUS_GROUPS_PERMISSIONS.put("CAMERA", Arrays.asList("CAMERA"));
        DANGEROUS_GROUPS_PERMISSIONS.put("CONTACTS", Arrays.asList("READ_CONTACTS", "WRITE_CONTACTS", "GET_ACCOUNTS"));
        DANGEROUS_GROUPS_PERMISSIONS.put("LOCATION", Arrays.asList("ACCESS_FINE_LOCATION", "ACCESS_COARSE_LOCATION"));
        DANGEROUS_GROUPS_PERMISSIONS.put("MICROPHONE", Arrays.asList("RECORD_AUDIO"));
        DANGEROUS_GROUPS_PERMISSIONS.put("PHONE", Arrays.asList("READ_PHONE_STATE", "CALL_PHONE",
                "READ_CALL_LOG", "WRITE_CALL_LOG", "ADD_VOICEMAIL", "USE_SIP", "PROCESS_OUTGOING_CALLS"));
        DANGEROUS_GROUPS_PERMISSIONS.put("SENSORS", Arrays.asList("BODY_SENSORS"));
        DANGEROUS_GROUPS_PERMISSIONS.put("SMS", Arrays.asList("SEND_SMS",
                "RECEIVE_SMS", "READ_SMS", "RECEIVE_WAP_PUSH", "RECEIVE_MMS"));
        DANGEROUS_GROUPS_PERMISSIONS.put("STORAGE", Arrays.asList("READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE"));
    }
}
